[#375] Handle missing aud claim in access token
irods/irods_client_http_api pull request #376
Opened 2024-11-29 11:23 UTC by ll4strw

Reject access tokens without aud claim

2024-12-02 20:07 UTC, MartinFlores751 requested changes
The change is very nice and simple. I like it.

Based on the discussions in the issue, we should have this be optional.

I'm suggesting we have a new configuration option `strict_introspection_endpoint_aud` to opt in to the strict check.

The name can change, of course. Open to suggestions.

2024-12-02 20:07 UTC, MartinFlores751 commented on core/src/openid.cpp
We would need to add the new configuration variable into `core/src/main.cpp`, in the schema:
https://github.com/irods/irods_client_http_api/blob/3824a09215a4b9b7e934178f2a7aa77b9654aa87/core/src/main.cpp#L208-L260

Something like the following should be fine:
```diff
                                "nonstandard_id_token_secret": {{
                                    "type": "string"
                                }},
+                               "strict_introspection_endpoint_aud": {{
+                                   "type": "boolean"
+                               }},
```

After that, we need to add the documentation for the new option in the README:
https://github.com/irods/irods_client_http_api/blob/3824a09215a4b9b7e934178f2a7aa77b9654aa87/README.md?plain=1#L253-L264

2024-12-02 20:16 UTC, korydraughn commented
@MartinFlores751 You can also make these edits and push to @ll4strw's branch.

2024-12-02 20:25 UTC, korydraughn commented
And if you can't do that or feel comfortable doing that, you can create a branch from @ll4strw's, edit it, and then open another PR.

Either approach is fine, but whatever you do, make sure to leave a comment here so the story is clear to everyone.

2024-12-02 20:38 UTC, MartinFlores751 commented
Gotcha, I'll create a branch and open it in another PR.

2024-12-02 20:49 UTC, MartinFlores751 commented on core/src/openid.cpp
> +		} else {
Handled in #378.

2024-12-02 20:49 UTC, korydraughn commented
Once @MartinFlores751 resolves the review comments, we'll give the approval for merging.

2024-12-02 20:49 UTC, MartinFlores751 commented on core/src/openid.cpp
Handled in #378.

2024-12-02 20:52 UTC, MartinFlores751 commented on core/src/openid.cpp
> +		} else {
This may be resolved.

2024-12-02 20:52 UTC, MartinFlores751 commented on core/src/openid.cpp
This may be resolved.

2024-12-02 21:07 UTC, korydraughn commented
Let's hold on merging this until #378 is complete.

2024-12-12 22:24 UTC, korydraughn commented
#378 is now complete.

Merging.

2024-12-12 22:24 UTC, korydraughn approved these changes

2024-12-12 22:25 UTC, merged